"""F3 form column definitions.

F3 is used for House and Senate campaign reports.

FEC Electronic Filing Format v8.5
See: https://www.fec.gov/campaign-finance-data/e-filing-parse-tool/
Column definitions source: https://github.com/newsdev/fec-csv-sources
"""

from ..constants import HeaderDef

F3_COLUMNS: list[HeaderDef] = [
    ("Form Type", "text"),
    ("Committee ID", "id"),
    ("Committee Name", "text"),
    ("Change of Address", "text"),
    ("Street 1", "text"),
    ("Street 2", "text"),
    ("City", "text"),
    ("State", "text"),
    ("ZIP", "text"),
    ("Election State", "text"),
    ("Election District", "text"),
    ("Report Code", "text"),
    ("Election Code", "text"),
    ("Election Date", "date"),
    ("State of Election", "text"),
    ("Coverage From Date", "date"),
    ("Coverage Through Date", "date"),
    ("Treasurer Last Name", "text"),
    ("Treasurer First Name", "text"),
    ("Treasurer Middle Name", "text"),
    ("Treasurer Prefix", "text"),
    ("Treasurer Suffix", "text"),
    ("Date Signed", "date"),
    ("Total Contributions (No Loans) - Period", "currency"),
    ("Total Contribution Refunds - Period", "currency"),
    ("Net Contributions - Period", "currency"),
    ("Total Operating Expenditures - Period", "currency"),
    ("Total Offset to Operating Expenditures - Period", "currency"),
    ("Net Operating Expenditures - Period", "currency"),
    ("Cash on Hand Close of Period", "currency"),
    ("Debts To", "currency"),
    ("Debts By", "currency"),
    ("Individual Contributions Itemized - Period", "currency"),
    ("Individual Contributions Unitemized - Period", "currency"),
    ("Total Individual Contributions - Period", "currency"),
    ("Political Party Contributions - Period", "currency"),
    ("PAC Contributions - Period", "currency"),
    ("Candidate Contributions - Period", "currency"),
    ("Total Contributions - Period", "currency"),
    ("Transfers From Authorized - Period", "currency"),
    ("Candidate Loans - Period", "currency"),
    ("Other Loans - Period", "currency"),
    ("Total Loans - Period", "currency"),
    ("Offset to Operating Expenditures - Period", "currency"),
    ("Other Receipts - Period", "currency"),
    ("Total Receipts - Period", "currency"),
    ("Operating Expenditures - Period", "currency"),
    ("Transfers to Authorized - Period", "currency"),
    ("Candidate Loan Repayments - Period", "currency"),
    ("Other Loan Repayments - Period", "currency"),
    ("Total Loan Repayments - Period", "currency"),
    ("Refunds to Individuals - Period", "currency"),
    ("Refunds to Party Committees - Period", "currency"),
    ("Refunds to Other Committees - Period", "currency"),
    ("Total Refunds - Period", "currency"),
    ("Other Disbursements - Period", "currency"),
    ("Total Disbursements - Period", "currency"),
    ("Cash on Hand Beginning of Period", "currency"),
    ("Total Receipts This Period", "currency"),
    ("Subtotals", "currency"),
    ("Total Disbursements This Period", "currency"),
    ("Cash on Hand Close", "currency"),
    ("Total Contributions (No Loans) - Cycle", "currency"),
    ("Total Contribution Refunds - Cycle", "currency"),
    ("Net Contributions - Cycle", "currency"),
    ("Total Operating Expenditures - Cycle", "currency"),
    ("Total Offset to Operating Expenditures - Cycle", "currency"),
    ("Net Operating Expenditures - Cycle", "currency"),
    ("Individual Contributions Itemized - Cycle", "currency"),
    ("Individual Contributions Unitemized - Cycle", "currency"),
    ("Total Individual Contributions - Cycle", "currency"),
    ("Political Party Contributions - Cycle", "currency"),
    ("PAC Contributions - Cycle", "currency"),
    ("Candidate Contributions - Cycle", "currency"),
    ("Total Contributions - Cycle", "currency"),
    ("Transfers From Authorized - Cycle", "currency"),
    ("Candidate Loans - Cycle", "currency"),
    ("Other Loans - Cycle", "currency"),
    ("Total Loans - Cycle", "currency"),
    ("Offset to Operating Expenditures - Cycle", "currency"),
    ("Other Receipts - Cycle", "currency"),
    ("Total Receipts - Cycle", "currency"),
    ("Operating Expenditures - Cycle", "currency"),
    ("Transfers to Authorized - Cycle", "currency"),
    ("Candidate Loan Repayments - Cycle", "currency"),
    ("Other Loan Repayments - Cycle", "currency"),
    ("Total Loan Repayments - Cycle", "currency"),
    ("Refunds to Individuals - Cycle", "currency"),
    ("Refunds to Party Committees - Cycle", "currency"),
    ("Refunds to Other Committees - Cycle", "currency"),
    ("Total Refunds - Cycle", "currency"),
    ("Other Disbursements - Cycle", "currency"),
    ("Total Disbursements - Cycle", "currency"),
]

SCHEDULE_A_COLUMNS: list[HeaderDef] = [
    ("Form Type", "text"),
    ("Committee ID", "id"),
    ("Transaction ID", "id"),
    ("Back Reference Transaction ID", "id"),
    ("Back Reference Schedule", "text"),
    ("Entity Type", "text"),
    ("Organization Name", "text"),
    ("Last Name", "text"),
    ("First Name", "text"),
    ("Middle Name", "text"),
    ("Prefix", "text"),
    ("Suffix", "text"),
    ("Street 1", "text"),
    ("Street 2", "text"),
    ("City", "text"),
    ("State", "text"),
    ("ZIP", "text"),
    ("Election Code", "text"),
    ("Election Other Description", "text"),
    ("Contribution Date", "date"),
    ("Contribution Amount", "currency"),
    ("Contribution Aggregate", "currency"),
    ("Contribution Purpose Description", "text"),
    ("Contributor Employer", "text"),
    ("Contributor Occupation", "text"),
    ("Donor Committee FEC ID", "id"),
    ("Donor Committee Name", "text"),
    ("Donor Candidate FEC ID", "id"),
    ("Donor Candidate Last Name", "text"),
    ("Donor Candidate First Name", "text"),
    ("Donor Candidate Middle Name", "text"),
    ("Donor Candidate Prefix", "text"),
    ("Donor Candidate Suffix", "text"),
    ("Donor Candidate Office", "text"),
    ("Donor Candidate State", "text"),
    ("Donor Candidate District", "text"),
    ("Conduit Name", "text"),
    ("Conduit Street 1", "text"),
    ("Conduit Street 2", "text"),
    ("Conduit City", "text"),
    ("Conduit State", "text"),
    ("Conduit ZIP", "text"),
    ("Memo Code", "text"),
    ("Memo / Earmark Info", "text"),
    ("Reference Code", "text"),
]

SCHEDULE_B_COLUMNS: list[HeaderDef] = [
    ("Form Type", "text"),
    ("Committee ID", "id"),
    ("Transaction ID", "id"),
    ("Back Reference Transaction ID", "id"),
    ("Back Reference Schedule", "text"),
    ("Entity Type", "text"),
    ("Payee Organization Name", "text"),
    ("Payee Last Name", "text"),
    ("Payee First Name", "text"),
    ("Payee Middle Name", "text"),
    ("Payee Prefix", "text"),
    ("Payee Suffix", "text"),
    ("Payee Street 1", "text"),
    ("Payee Street 2", "text"),
    ("Payee City", "text"),
    ("Payee State", "text"),
    ("Payee ZIP", "text"),
    ("Election Code", "text"),
    ("Election Other Description", "text"),
    ("Expenditure Date", "date"),
    ("Expenditure Amount", "currency"),
    ("Semi-Annual Refunded Bundled Amount", "currency"),
    ("Expenditure Purpose Description", "text"),
    ("Category Code", "text"),
    ("Beneficiary Committee FEC ID", "id"),
    ("Beneficiary Committee Name", "text"),
    ("Beneficiary Candidate FEC ID", "id"),
    ("Beneficiary Candidate Last Name", "text"),
    ("Beneficiary Candidate First Name", "text"),
    ("Beneficiary Candidate Middle Name", "text"),
    ("Beneficiary Candidate Prefix", "text"),
    ("Beneficiary Candidate Suffix", "text"),
    ("Beneficiary Candidate Office", "text"),
    ("Beneficiary Candidate State", "text"),
    ("Beneficiary Candidate District", "text"),
    ("Conduit Name", "text"),
    ("Conduit Street 1", "text"),
    ("Conduit Street 2", "text"),
    ("Conduit City", "text"),
    ("Conduit State", "text"),
    ("Conduit ZIP", "text"),
    ("Memo Code", "text"),
    ("Memo / Earmark Info", "text"),
    ("Reference Code", "text"),
]

# Header name lists
F3_HEADERS: list[str] = [col[0] for col in F3_COLUMNS]
SCHEDULE_A_HEADERS: list[str] = [col[0] for col in SCHEDULE_A_COLUMNS]
SCHEDULE_B_HEADERS: list[str] = [col[0] for col in SCHEDULE_B_COLUMNS]

# Form type prefix to headers mapping for F3 forms
F3_FORM_TYPE_HEADERS: dict[str, list[str]] = {
    "F3": F3_HEADERS,
    "SA": SCHEDULE_A_HEADERS,
    "SB": SCHEDULE_B_HEADERS,
}

F3_FORM_TYPE_COLUMNS: dict[str, list[HeaderDef]] = {
    "F3": F3_COLUMNS,
    "SA": SCHEDULE_A_COLUMNS,
    "SB": SCHEDULE_B_COLUMNS,
}
