"""Prompt templates for AI analysis."""

from .grouped_donations import (
    GROUPED_DONATIONS_SYSTEM_PROMPT,
    GROUPED_DONATIONS_USER_TEMPLATE,
)
from .industry import INDUSTRY_SYSTEM_PROMPT, INDUSTRY_USER_TEMPLATE
from .summary import SUMMARY_SYSTEM_PROMPT, SUMMARY_USER_TEMPLATE
from .unusual_expenditures import (
    UNUSUAL_EXPENDITURES_SYSTEM_PROMPT,
    UNUSUAL_EXPENDITURES_USER_TEMPLATE,
)

__all__ = [
    "GROUPED_DONATIONS_SYSTEM_PROMPT",
    "GROUPED_DONATIONS_USER_TEMPLATE",
    "INDUSTRY_SYSTEM_PROMPT",
    "INDUSTRY_USER_TEMPLATE",
    "SUMMARY_SYSTEM_PROMPT",
    "SUMMARY_USER_TEMPLATE",
    "UNUSUAL_EXPENDITURES_SYSTEM_PROMPT",
    "UNUSUAL_EXPENDITURES_USER_TEMPLATE",
]
