"""Prompt templates for AI analysis."""

from .expenditure_analysis import (
    EXPENDITURE_ANALYSIS_SYSTEM_PROMPT,
    EXPENDITURE_ANALYSIS_USER_TEMPLATE,
)
from .grouped_donations import (
    GROUPED_DONATIONS_SYSTEM_PROMPT,
    GROUPED_DONATIONS_USER_TEMPLATE,
)
from .industry import INDUSTRY_SYSTEM_PROMPT, INDUSTRY_USER_TEMPLATE
from .summary import SUMMARY_SYSTEM_PROMPT, SUMMARY_USER_TEMPLATE

__all__ = [
    "EXPENDITURE_ANALYSIS_SYSTEM_PROMPT",
    "EXPENDITURE_ANALYSIS_USER_TEMPLATE",
    "GROUPED_DONATIONS_SYSTEM_PROMPT",
    "GROUPED_DONATIONS_USER_TEMPLATE",
    "INDUSTRY_SYSTEM_PROMPT",
    "INDUSTRY_USER_TEMPLATE",
    "SUMMARY_SYSTEM_PROMPT",
    "SUMMARY_USER_TEMPLATE",
]
