"""Constants for FEC data services."""

from typing import get_args

from fec_api_client.types import ReportTypeCode

# FEC quarterly report type codes (subset of ReportTypeCode)
# Q1: April Quarterly (covers January 1 - March 31)
# Q2: July Quarterly (covers April 1 - June 30)
# Q3: October Quarterly (covers July 1 - September 30)
# YE: Year-End (covers October 1 - December 31)
QUARTERLY_REPORT_TYPES: list[ReportTypeCode] = ["Q1", "Q2", "Q3", "YE"]

# All valid FEC report type codes (from ReportTypeCode Literal)
ALL_REPORT_TYPES: list[ReportTypeCode] = list(get_args(ReportTypeCode))

# =============================================================================
# FEC CSV Headers (version 8.x with friendly display names)
# Source: https://github.com/newsdev/fec-csv-sources
# =============================================================================

HDR_HEADERS = [
    "Record Type",
    "EF Type",
    "FEC Version",
    "Software Name",
    "Software Version",
    "Name Delimiter",
    "Report ID",
    "Report Number",
    "Comment",
]

# Form 3 (F3/F3N) headers - main filing summary
F3_HEADERS = [
    "Form Type",
    "Committee ID",
    "Committee Name",
    "Change of Address",
    "Street 1",
    "Street 2",
    "City",
    "State",
    "ZIP",
    "Election State",
    "Election District",
    "Report Code",
    "Election Code",
    "Election Date",
    "State of Election",
    "Coverage From Date",
    "Coverage Through Date",
    "Treasurer Last Name",
    "Treasurer First Name",
    "Treasurer Middle Name",
    "Treasurer Prefix",
    "Treasurer Suffix",
    "Date Signed",
    "Total Contributions (No Loans) - Period",
    "Total Contribution Refunds - Period",
    "Net Contributions - Period",
    "Total Operating Expenditures - Period",
    "Total Offset to Operating Expenditures - Period",
    "Net Operating Expenditures - Period",
    "Cash on Hand Close of Period",
    "Debts To",
    "Debts By",
    "Individual Contributions Itemized - Period",
    "Individual Contributions Unitemized - Period",
    "Total Individual Contributions - Period",
    "Political Party Contributions - Period",
    "PAC Contributions - Period",
    "Candidate Contributions - Period",
    "Total Contributions - Period",
    "Transfers From Authorized - Period",
    "Candidate Loans - Period",
    "Other Loans - Period",
    "Total Loans - Period",
    "Offset to Operating Expenditures - Period",
    "Other Receipts - Period",
    "Total Receipts - Period",
    "Operating Expenditures - Period",
    "Transfers to Authorized - Period",
    "Candidate Loan Repayments - Period",
    "Other Loan Repayments - Period",
    "Total Loan Repayments - Period",
    "Refunds to Individuals - Period",
    "Refunds to Party Committees - Period",
    "Refunds to Other Committees - Period",
    "Total Refunds - Period",
    "Other Disbursements - Period",
    "Total Disbursements - Period",
    "Cash on Hand Beginning of Period",
    "Total Receipts This Period",
    "Subtotals",
    "Total Disbursements This Period",
    "Cash on Hand Close",
    "Total Contributions (No Loans) - Cycle",
    "Total Contribution Refunds - Cycle",
    "Net Contributions - Cycle",
    "Total Operating Expenditures - Cycle",
    "Total Offset to Operating Expenditures - Cycle",
    "Net Operating Expenditures - Cycle",
    "Individual Contributions Itemized - Cycle",
    "Individual Contributions Unitemized - Cycle",
    "Total Individual Contributions - Cycle",
    "Political Party Contributions - Cycle",
    "PAC Contributions - Cycle",
    "Candidate Contributions - Cycle",
    "Total Contributions - Cycle",
    "Transfers From Authorized - Cycle",
    "Candidate Loans - Cycle",
    "Other Loans - Cycle",
    "Total Loans - Cycle",
    "Offset to Operating Expenditures - Cycle",
    "Other Receipts - Cycle",
    "Total Receipts - Cycle",
    "Operating Expenditures - Cycle",
    "Transfers to Authorized - Cycle",
    "Candidate Loan Repayments - Cycle",
    "Other Loan Repayments - Cycle",
    "Total Loan Repayments - Cycle",
    "Refunds to Individuals - Cycle",
    "Refunds to Party Committees - Cycle",
    "Refunds to Other Committees - Cycle",
    "Total Refunds - Cycle",
    "Other Disbursements - Cycle",
    "Total Disbursements - Cycle",
]

# Schedule A headers (contributions) - SA11AI, SA11C, SA12, SA14, etc.
SCHEDULE_A_HEADERS = [
    "Form Type",
    "Committee ID",
    "Transaction ID",
    "Back Reference Transaction ID",
    "Back Reference Schedule",
    "Entity Type",
    "Organization Name",
    "Last Name",
    "First Name",
    "Middle Name",
    "Prefix",
    "Suffix",
    "Street 1",
    "Street 2",
    "City",
    "State",
    "ZIP",
    "Election Code",
    "Election Other Description",
    "Date",
    "Amount",
    "Aggregate",
    "Purpose Code",
    "Purpose Description",
    "Employer",
    "Occupation",
    "Donor Committee FEC ID",
    "Donor Committee Name",
    "Donor Candidate FEC ID",
    "Donor Candidate Last Name",
    "Donor Candidate First Name",
    "Donor Candidate Middle Name",
    "Donor Candidate Prefix",
    "Donor Candidate Suffix",
    "Donor Candidate Office",
    "Donor Candidate State",
    "Donor Candidate District",
    "Conduit Name",
    "Conduit Street 1",
    "Conduit Street 2",
    "Conduit City",
    "Conduit State",
    "Conduit ZIP",
    "Memo Code",
    "Memo / Earmark Info",
    "Reference Code",
]

# Schedule B headers (disbursements) - SB17, SB20A, SB21, etc.
SCHEDULE_B_HEADERS = [
    "Form Type",
    "Committee ID",
    "Transaction ID",
    "Back Reference Transaction ID",
    "Back Reference Schedule",
    "Entity Type",
    "Payee Organization Name",
    "Payee Last Name",
    "Payee First Name",
    "Payee Middle Name",
    "Payee Prefix",
    "Payee Suffix",
    "Payee Street 1",
    "Payee Street 2",
    "Payee City",
    "Payee State",
    "Payee ZIP",
    "Election Code",
    "Election Other Description",
    "Date",
    "Amount",
    "Semi-Annual Refunded Bundled Amount",
    "Purpose Code",
    "Purpose Description",
    "Category Code",
    "Beneficiary Committee FEC ID",
    "Beneficiary Committee Name",
    "Beneficiary Candidate FEC ID",
    "Beneficiary Candidate Last Name",
    "Beneficiary Candidate First Name",
    "Beneficiary Candidate Middle Name",
    "Beneficiary Candidate Prefix",
    "Beneficiary Candidate Suffix",
    "Beneficiary Candidate Office",
    "Beneficiary Candidate State",
    "Beneficiary Candidate District",
    "Conduit Name",
    "Conduit Street 1",
    "Conduit Street 2",
    "Conduit City",
    "Conduit State",
    "Conduit ZIP",
    "Memo Code",
    "Memo / Earmark Info",
    "Reference Code",
]

# Mapping of form type prefixes to their headers
FORM_TYPE_HEADERS: dict[str, list[str]] = {
    "HDR": HDR_HEADERS,
    "F3": F3_HEADERS,
    "SA": SCHEDULE_A_HEADERS,
    "SB": SCHEDULE_B_HEADERS,
}
